# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order-service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'order-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UserService_pb2 as UserService__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order-service.proto\x12\x05order\x1a\x11UserService.proto\"F\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x05items\x18\x02 \x03(\x0b\x32\x10.order.OrderItem\"\\\n\x13\x43reateOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x05order\x18\x03 \x01(\x0b\x32\x14.order.OrderWithUser\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"Y\n\x10GetOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x05order\x18\x03 \x01(\x0b\x32\x14.order.OrderWithUser\"\'\n\x14GetUserOrdersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"_\n\x15GetUserOrdersResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12$\n\x06orders\x18\x03 \x03(\x0b\x32\x14.order.OrderWithUser\"\x7f\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x1f\n\x05items\x18\x03 \x03(\x0b\x32\x10.order.OrderItem\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"B\n\tOrderItem\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"F\n\rOrderWithUser\x12\x1b\n\x05order\x18\x01 \x01(\x0b\x32\x0c.order.Order\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.user.User2\xdd\x01\n\x0cOrderService\x12\x44\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12;\n\x08GetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12J\n\rGetUserOrders\x12\x1b.order.GetUserOrdersRequest\x1a\x1c.order.GetUserOrdersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=49
  _globals['_CREATEORDERREQUEST']._serialized_end=119
  _globals['_CREATEORDERRESPONSE']._serialized_start=121
  _globals['_CREATEORDERRESPONSE']._serialized_end=213
  _globals['_GETORDERREQUEST']._serialized_start=215
  _globals['_GETORDERREQUEST']._serialized_end=250
  _globals['_GETORDERRESPONSE']._serialized_start=252
  _globals['_GETORDERRESPONSE']._serialized_end=341
  _globals['_GETUSERORDERSREQUEST']._serialized_start=343
  _globals['_GETUSERORDERSREQUEST']._serialized_end=382
  _globals['_GETUSERORDERSRESPONSE']._serialized_start=384
  _globals['_GETUSERORDERSRESPONSE']._serialized_end=479
  _globals['_ORDER']._serialized_start=481
  _globals['_ORDER']._serialized_end=608
  _globals['_ORDERITEM']._serialized_start=610
  _globals['_ORDERITEM']._serialized_end=676
  _globals['_ORDERWITHUSER']._serialized_start=678
  _globals['_ORDERWITHUSER']._serialized_end=748
  _globals['_ORDERSERVICE']._serialized_start=751
  _globals['_ORDERSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
